/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.mvc.view;

import edu.ijse.mvc.controller.ItemController;
import edu.ijse.mvc.dto.ItemDto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Isuru Manchanayake
 */
public class ItemView extends javax.swing.JFrame {
       private  ItemController itemController;
    /**
     * Creates new form ItemView
     * @throws java.lang.Exception
     */
    public ItemView() throws Exception {
        initComponents();
        itemController = new ItemController();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesc1 = new javax.swing.JLabel();
        jTextDesc1 = new javax.swing.JTextField();
        jTextPack = new javax.swing.JTextField();
        jTitle = new javax.swing.JLabel();
        jCode = new javax.swing.JLabel();
        jTextCode = new javax.swing.JTextField();
        jDesc = new javax.swing.JLabel();
        jTextDesc = new javax.swing.JTextField();
        jPack = new javax.swing.JLabel();
        jPrice = new javax.swing.JLabel();
        jTextPrice = new javax.swing.JTextField();
        JQoh = new javax.swing.JLabel();
        jTextQoh = new javax.swing.JTextField();
        jSave = new javax.swing.JButton();
        jUpdate = new javax.swing.JButton();
        JCancel = new javax.swing.JButton();
        jTextPackSize = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();

        jDesc1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jDesc1.setText("Description");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitle.setText("Item Form");

        jCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCode.setText("Code");

        jDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jDesc.setText("Description");

        jPack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPack.setText("Pack size");

        jPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPrice.setText("Unit Price");

        JQoh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JQoh.setText("Qoh");

        jSave.setText("Save");
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });

        jUpdate.setText("Update");
        jUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateActionPerformed(evt);
            }
        });

        JCancel.setText("Cancel");
        JCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCancelActionPerformed(evt);
            }
        });

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSave)))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDesc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(jTextCode)
                            .addComponent(jTextPackSize))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JQoh, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextQoh, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextQoh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JQoh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPack, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPackSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSave)
                    .addComponent(jUpdate)
                    .addComponent(JCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateActionPerformed
        updateItem();
    }//GEN-LAST:event_jUpdateActionPerformed

    private void JCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCancelActionPerformed
        cancelItem();
    }//GEN-LAST:event_JCancelActionPerformed

    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed
        saveItem();
    }//GEN-LAST:event_jSaveActionPerformed

    private void tblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemMouseClicked
        searchItem();
    }//GEN-LAST:event_tblItemMouseClicked

    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
   //      * For details see http://download.oracle.com/javase/tutorial/uis
         */
   //     try {
  //          for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
  //              if ("Nimbus".equals(info.getName())) {
  //                  javax.swing.UIManager.setLookAndFeel(info.getClassName());
  //                  break;
  //              }
  //          }
  //      } catch (ClassNotFoundException ex) {
  //          java.util.logging.Logger.getLogger(ItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  //      } catch (InstantiationException ex) {
  //          java.util.logging.Logger.getLogger(ItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  //      } catch (IllegalAccessException ex) {
  //          java.util.logging.Logger.getLogger(ItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  //      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
  //          java.util.logging.Logger.getLogger(ItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
   //     }
        //</editor-fold>

        /* Create and display the form */
   //     java.awt.EventQueue.invokeLater(new Runnable() {
   //         public void run() {
   //             new ItemView().setVisible(true);
   //         }
   //     });
 //   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JCancel;
    private javax.swing.JLabel JQoh;
    private javax.swing.JLabel jCode;
    private javax.swing.JLabel jDesc;
    private javax.swing.JLabel jDesc1;
    private javax.swing.JLabel jPack;
    private javax.swing.JLabel jPrice;
    private javax.swing.JButton jSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextCode;
    private javax.swing.JTextField jTextDesc;
    private javax.swing.JTextField jTextDesc1;
    private javax.swing.JTextField jTextPack;
    private javax.swing.JTextField jTextPackSize;
    private javax.swing.JTextField jTextPrice;
    private javax.swing.JTextField jTextQoh;
    private javax.swing.JLabel jTitle;
    private javax.swing.JButton jUpdate;
    private javax.swing.JTable tblItem;
    // End of variables declaration//GEN-END:variables

    private void saveItem(){
    try {
      ItemDto dto=new ItemDto(jTextCode.getText(),jTextDesc.getText(),jTextPackSize.getText(),Double.parseDouble(jTextPrice.getText()),Integer.parseInt(jTextQoh.getText()));
          String resp = itemController.saveItem(dto);
           // System.out.println(resp);
            JOptionPane.showMessageDialog(this, resp);
            clearForm();
            loadTable();
        } catch (Exception ex) {
           // Logger.getLogger(ItemView.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(this, "Error at save data");
           clearForm();
           
        }
      
     }
    private void clearForm(){
       jTextCode.setText("");
       jTextDesc.setText("");
       jTextPackSize.setText("");
       jTextPrice.setText("");
       jTextQoh.setText("");
    }
   private void loadTable(){
       try {
           String columns[]={"Item ID","Item Description","Pack size","Unit price","QoH"};
           DefaultTableModel dtm=new DefaultTableModel(columns,0){
               @Override
              public boolean isCellEditable(int row, int column){
                 return false;
              }
           };
           tblItem.setModel(dtm);
           
           ArrayList<ItemDto>itemDtos = itemController.getAllItem();
           for(ItemDto dto : itemDtos){
             Object[] rowData = {dto.getCode(),dto.getDescription(),dto.getPackSize(),dto.getUnitPrice(),dto.getQoh()};
             dtm.addRow(rowData);
           }
       } catch (Exception e) {
           JOptionPane.showMessageDialog(this, "Error at loading Data to item table");
       }
   } 
 public void searchItem(){
     try {
       String itemId = tblItem.getValueAt(tblItem.getSelectedRow(), 0).toString();
       ItemDto dto=itemController.searchItem(itemId);
       
       if(dto != null){
          jTextCode.setText(dto.getCode());
          jTextDesc.setText(dto.getDescription());
          jTextPackSize.setText(dto.getPackSize());
          jTextPrice.setText(Double.toString(dto.getUnitPrice()));
          jTextQoh.setText(Integer.toString(dto.getQoh()));
       }else{
          JOptionPane.showMessageDialog(this, "Item not found");
       }
     } catch (Exception e) {
         JOptionPane.showMessageDialog(this, "Error at loading Item");
     }
 }
 
 public void cancelItem(){
     try {
         String itemCode = jTextCode.getText();
         String resp = itemController.cancelItem(itemCode);
         JOptionPane.showMessageDialog(this, resp);
            clearForm();
            loadTable();
         
     } catch (Exception e) {
         JOptionPane.showMessageDialog(this, "Error at Cancel Item");
     }
 }
 
 private void updateItem(){
    try {
      ItemDto itemDto=new ItemDto(jTextCode.getText(),jTextDesc.getText(),jTextPackSize.getText(),Double.parseDouble(jTextPrice.getText()),Integer.parseInt(jTextQoh.getText()));
          String resp = itemController.updateItem(itemDto);
           // System.out.println(resp);
            JOptionPane.showMessageDialog(this, resp);
            loadTable();
            clearForm();
            
        } catch (Exception ex) {
           // Logger.getLogger(ItemView.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(this, "Error at update data");
           clearForm();
           
        }
      
     }
}
