/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.mvc.view;

import edu.ijse.mvc.controller.CustController;
import edu.ijse.mvc.dto.ItemDto;
import edu.ijse.mvc.controller.ItemController;
import edu.ijse.mvc.controller.OrderController;
import edu.ijse.mvc.dto.CustDto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import edu.ijse.mvc.dto.OrderDetailDto;
import java.util.ArrayList;
import edu.ijse.mvc.dto.OrderDto;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Isuru Manchanayake
 */
public class OrderView extends javax.swing.JFrame {

    /**
     * Creates new form OrderView
     */
    private ItemController itemController;
    private CustController custController;
    private ArrayList<OrderDetailDto>orderDetailDtos;
    private OrderController orderController;
    
    
    public OrderView() throws Exception {
        custController = new CustController();
        itemController = new ItemController();
        orderDetailDtos = new ArrayList<>();
        orderController = new OrderController();
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLOrder = new javax.swing.JLabel();
        jLOrderId = new javax.swing.JLabel();
        jTextOrderId = new javax.swing.JTextField();
        jLCustId = new javax.swing.JLabel();
        jTextCustId = new javax.swing.JTextField();
        jBtnSearch = new javax.swing.JButton();
        jLCustDetail = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLItemId = new javax.swing.JLabel();
        jTextItemId = new javax.swing.JTextField();
        jBtnItemSearch = new javax.swing.JButton();
        jLItemDetail = new javax.swing.JLabel();
        jLDiscount = new javax.swing.JLabel();
        jTextDiscount = new javax.swing.JTextField();
        jLQty = new javax.swing.JLabel();
        jTextQty = new javax.swing.JTextField();
        jBtnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOrder = new javax.swing.JTable();
        jBtnPlOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLOrder.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLOrder.setText("Place Order");

        jLOrderId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLOrderId.setText("Order ID");

        jLCustId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLCustId.setText("Customer ID");

        jBtnSearch.setText("Search");
        jBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchActionPerformed(evt);
            }
        });

        jLItemId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLItemId.setText("Item Id");

        jBtnItemSearch.setText("Search");
        jBtnItemSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnItemSearchActionPerformed(evt);
            }
        });

        jLDiscount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLDiscount.setText("Discount");

        jLQty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLQty.setText("Qty");

        jBtnAdd.setText("Add");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });

        jTableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableOrder);

        jBtnPlOrder.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnPlOrder.setText("Place Order");
        jBtnPlOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPlOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLItemId, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jTextItemId, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnItemSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLItemDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jTextDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLQty, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextQty, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jBtnAdd))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jTextOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLCustId, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jTextCustId, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnSearch)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLCustDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 8, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtnPlOrder)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCustId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnSearch)
                            .addComponent(jLCustDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCustId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLItemId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnItemSearch)
                            .addComponent(jLItemDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextItemId, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnAdd)
                            .addComponent(jLQty, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jBtnPlOrder)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnItemSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnItemSearchActionPerformed
        searchItem();
    }//GEN-LAST:event_jBtnItemSearchActionPerformed

    private void jBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchActionPerformed
        searchCustomer();
    }//GEN-LAST:event_jBtnSearchActionPerformed

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        addToTable();
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnPlOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPlOrderActionPerformed
        placeOrder();
    }//GEN-LAST:event_jBtnPlOrderActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
     /*   java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderView().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnItemSearch;
    private javax.swing.JButton jBtnPlOrder;
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JLabel jLCustDetail;
    private javax.swing.JLabel jLCustId;
    private javax.swing.JLabel jLDiscount;
    private javax.swing.JLabel jLItemDetail;
    private javax.swing.JLabel jLItemId;
    private javax.swing.JLabel jLOrder;
    private javax.swing.JLabel jLOrderId;
    private javax.swing.JLabel jLQty;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableOrder;
    private javax.swing.JTextField jTextCustId;
    private javax.swing.JTextField jTextDiscount;
    private javax.swing.JTextField jTextItemId;
    private javax.swing.JTextField jTextOrderId;
    private javax.swing.JTextField jTextQty;
    // End of variables declaration//GEN-END:variables
  private void searchItem(){
      try {
          String itemId = jTextItemId.getText();
          ItemDto itemdto = itemController.searchItem(itemId);
          if(itemdto != null){
          jLItemDetail.setText(itemdto.getCode()+ " | "+itemdto.getDescription()+" : "+itemdto.getQoh()+" : "+itemdto.getUnitPrice());
          }else{
          jLItemDetail.setText("Item not found");}
      } catch (Exception e) {
          e.printStackTrace();
          JOptionPane.showMessageDialog(this, "Error at search Item");
      }
  }
  
  private void searchCustomer(){
      try {
          String custId = jTextCustId.getText();
          CustDto custDto = custController.searchCustomer(custId);
          if(custDto != null){
             jLCustDetail.setText(custDto.getCustID()+" | "+custDto.getCustName()+" : "+custDto.getCustAddress());
          }else{
            jLCustDetail.setText("Customer not found");
          }
      } catch (Exception e) {
          e.printStackTrace();
          JOptionPane.showMessageDialog(this, "Error at search customer");
      }
  }

    private void loadTable() {
        String columns[] = {"Item Code", "Qty", "Discount"};
        DefaultTableModel dtm = new DefaultTableModel(columns, 0){
          @Override
          public boolean isCellEditable(int row, int column){
                  return false;
          }
        };
      jTableOrder.setModel(dtm);
    }

    private void addToTable() {
        OrderDetailDto orderDetailDto = new OrderDetailDto(null, jTextItemId.getText(), Integer.parseInt(jTextQty.getText()),
                Integer.parseInt(jTextDiscount.getText()));
        
        orderDetailDtos.add(orderDetailDto);
        
        Object[] rowData = {orderDetailDto.getItemCode(), orderDetailDto.getQty(), orderDetailDto.getDiscount()};
        DefaultTableModel dtm = (DefaultTableModel) jTableOrder.getModel();
        dtm.addRow(rowData);
        
        cleanItem();
    }

    private void cleanItem() {
        jTextItemId.setText("");
        jTextQty.setText("");
        jTextDiscount.setText("");
    }

    private void placeOrder() {
        try {
            OrderDto orderDto = new OrderDto();
            orderDto.setOrderId(jTextOrderId.getText());
            orderDto.setCustId(jTextCustId.getText());
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(new Date());
            orderDto.setDate(date);
            
            String resp = orderController.placeOrder(orderDto, orderDetailDtos);
            JOptionPane.showMessageDialog(this, resp);
        } catch(Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error at Order save");
        }
    }
    
    

}
